services:
    command_bus:
        class: NilPortugues\CommandBus
        arguments:
         - @service_container
         - %command_bus_map%

    validation_bus:
        class: NilPortugues\CommandValidationBus
        arguments:
         - @service_container
         - %validation_bus_map%
         - @command_bus
