nil_portugues_my_bounded_context_homepage:
    path:     /
    defaults: { _controller: NilPortuguesMyBoundedContextBundle:Default:index }


nil_portugues_my_bounded_context_register_user:
    path:     /user/register
    defaults: { _controller: NilPortuguesMyBoundedContextBundle:User:registerUser }

nil_portugues_my_bounded_context_new_user:
    path:     /user/sign_up
    defaults: { _controller: NilPortuguesMyBoundedContextBundle:User:newUser }

nil_portugues_my_bounded_context_view_user:
    path:     /user/{id}
    defaults: { _controller: NilPortuguesMyBoundedContextBundle:User:viewUser }

nil_portugues_my_bounded_context_view_post:
    path:     /blog/post/{postId}
    defaults: { _controller: NilPortuguesMyBoundedContextBundle:BlogPost:viewPost }
