imports:
    - { resource: parameters.yml }

services:
################################################################################################################
# USER
################################################################################################################
    nil_portugues.my_bounded_context.infrastructure.persistence.in_memory.user.user_repository:
        class: NilPortugues\MyBoundedContext\Infrastructure\Persistence\InMemory\User\UserRepository
        arguments: ["%user_array%"]

    nil_portugues.my_bounded_context.application.model.user.view_user.view_user_use_case:
        class: NilPortugues\MyBoundedContext\Application\Model\User\ViewUser\ViewUserUseCase
        arguments: [ @nil_portugues.my_bounded_context.infrastructure.persistence.in_memory.user.user_repository ]

################################################################################################################
# POST
################################################################################################################
    nil_portugues.my_bounded_context.infrastructure.persistence.in_memory.blog_post.post_repository:
        class: NilPortugues\MyBoundedContext\Infrastructure\Persistence\InMemory\BlogPost\PostRepository
        arguments: ["%post_array%"]

    nil_portugues.my_bounded_context.application.model.blog_post.view_post.view_post_use_case:
        class: NilPortugues\MyBoundedContext\Application\Model\BlogPost\ViewPost\ViewPostUseCase
        arguments: [ @nil_portugues.my_bounded_context.infrastructure.persistence.in_memory.blog_post.post_repository ]
