parameters:
  command_bus_map:
    "NilPortugues_MyBoundedContext_Application_Model_User_View_ViewUserCommand": nil_portugues.my_bounded_context.application.model.user.view_user.view_user_command_handler
    "NilPortugues_MyBoundedContext_Application_Model_User_SignUp_SignUpUserCommand": nil_portugues.my_bounded_context.application.model.user.sign_up.sign_up_user_command_handler
    "NilPortugues_MyBoundedContext_Application_Model_Blog_Post_ViewPost_ViewPostCommand": nil_portugues.my_bounded_context.application.model.blog_post.view_post.view_post_command_handler
