parameters:
  validation_bus_map:
    "NilPortugues_MyBoundedContext_Application_User_View_Command_ViewUserCommand": nil_portugues.my_bounded_context.application.user.view_user.command.view_user_command_validator
    "NilPortugues_MyBoundedContext_Application_User_SignUp_Command_SignUpUserCommand": nil_portugues.my_bounded_context.application.user.sign_up.command.sign_up_user_command_validator
    "NilPortugues_MyBoundedContext_Application_Blog_Post_ViewPost_Command_ViewPostCommand": nil_portugues.my_bounded_context.application.blog_post.view_post.command.view_post_command_validator
